---
- name: Run yolo backup with 'current' tag
  ansible.builtin.command: "{{ dci_db_backup_command }}"
  delegate_to: "{{ lookup('inventory_hostnames', yolo_backup_host_selector) | split(',') | sort | first }}"
  become: true
  become_user: "{{ yolo_backup_user | default('dci') }}"
  # Backups can take some time
  # To avoid ssh connection behaving badly (timeout, ansible not resuming after backup done)
  # we run as an async task, limiting it to 30 minutes and checking if it's done every 15 seconds
  async: 1800
  poll: 15
  changed_when: true
  when:
    - dci_db_backup_before_cs_upgrade | default(False)
