# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Enable SCL
  yum: name=centos-release-scl state=present
  tags:
    - dci-core

- name: Ensure PostgreSQL packages are installed
  yum: name={{item}} state=present
  with_items:
    - postgresql
# the sensu PostgreSQL check is linked against the postgresql client lib
    - postgresql-devel
# we keep installing the server even if we don't use it. This to have the
# postgresql service installed, as expected by ansible when it checks for
# the service with systemctl.
    - postgresql-server
    - rh-postgresql94-postgresql
    - rh-postgresql94-postgresql-devel
    - rh-postgresql94-postgresql-server
    - python-psycopg2
  tags:
    - dci-core

- name: Install sensu-plugins
  command: sensu-install -p {{item}}
  with_items:
    - postgres
  tags:
    - monitoring

- name: Ensure the regular PostgreSQL service is off. We use the one from SCL instead.
  service: name=postgresql state=stopped enabled=no
  tags:
    - dci-core

- stat: path=/opt/rh/rh-postgresql94/data
  register: pg_data_dir

- name: Move existing DB to the new location
  shell: mv /var/lib/pgsql/data /opt/rh/rh-postgresql94/data
  failed_when: "result.rc not in [ 0, 1 ]"
  register: move_old_db_data
  tags:
    - dci-core
  when: pg_data_dir.stat.isdir is not defined or not pg_data_dir.stat.isdir

- name: Initialize postgresql
  shell: /opt/rh/rh-postgresql94/root/bin/postgresql-setup initdb
  register: move_old_db_data
  tags:
     - dci-core
  when: pg_data_dir.stat.isdir is not defined or not pg_data_dir.stat.isdir and move_old_db_data|failed

- name: Ensure PostgreSQL listen to all addresses
  lineinfile: dest=/var/opt/rh/rh-postgresql94/lib/pgsql/data/postgresql.conf
              regexp="^listen_addresses = '*'"
              insertafter="^#\s+-\s+Connection Settings"
              line="listen_addresses = '*'"
  tags:
    - dci-core

- name: Ensure user can identify with password authentication mechanisms
  lineinfile: dest=/var/opt/rh/rh-postgresql94/lib/pgsql/data/pg_hba.conf
              regexp="^host\s+all\s+all\s+127\.0\.0\.1/32\s+{{item}}$"
              insertafter="^#\sIPv4\slocal.+"
              line="host    all             all  {{ apihost }}/32            {{item}}"
  with_items:
    - password
    - md5
  tags:
    - dci-core

- name: Ensure user can identify with password authentication mechanisms
  lineinfile: dest=/var/opt/rh/rh-postgresql94/lib/pgsql/data/pg_hba.conf
              regexp="^host\s+all\s+all\s+127\.0\.0\.1/32\s+{{item}}$"
              insertafter="^#\sIPv4\slocal.+"
              line="host    all             all  127.0.0.1/32            {{item}}"
  with_items:
    - password
    - md5
  tags:
    - dci-core

- name: Ensure PostgreSQL 9.4 service is started
  service: name=rh-postgresql94-postgresql state=started enabled=yes
  tags:
    - dci-core
#
# Create DCI database and user
#
- name: ensure database is created
  postgresql_db: name={{dbname}}
  become: yes
  become_user: postgres
  tags:
    - dci-core

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
  become: yes
  become_user: postgres
  tags:
    - dci-core

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=SUPERUSER,CREATEDB
  become: yes
  become_user: postgres
  tags:
    - dci-core
