---
elasticsearch_cluster_name: "elasticsearch"
elasticsearch_config:
  discovery.zen.minimum_master_nodes: 1
  action.auto_create_index: true
  indices.cache.cleanup_interval: "1m"
  network.host: "0.0.0.0"
  transport.host: "0.0.0.0"
  bootstrap.memory_lock: true
  node.master: true
  node.data: true
  node.ingest: true
  discovery.type: "single-node"
elasticsearch_container_name: "dci-elasticsearch"
elasticsearch_enabled: true
elasticsearch_gid: "0"
elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
elasticsearch_node_name: "{{ inventory_hostname }}"
elasticsearch_path: "/opt/elasticsearch"
elasticsearch_service: "elasticsearch"
elasticsearch_ssl_enabled: false
elasticsearch_ssl_key: "/usr/share/elasticsearch/config/certs/analytics.distributed-ci.io.key"
elasticsearch_ssl_crt: "/usr/share/elasticsearch/config/certs/analytics.distributed-ci.io.crt"
elasticsearch_ssl_ca: "/usr/share/elasticsearch/config/certs/ca.crt"
elasticsearch_sslcerts_path: "/etc/ssl/certs/analytics.distributed-ci.io/"
elasticsearch_uid: "1000"

elasticsearch_ports:
  - 9200:9200
  - 9300:9300

elasticsearch_volumes:
  - "{{ elasticsearch_path }}/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z"
  - "{{ elasticsearch_path }}/data:/usr/share/elasticsearch/data:Z"
  - "{{ elasticsearch_path }}/logs:/usr/share/elasticsearch/logs:Z"
  - "{{ elasticsearch_sslcerts_path }}:/usr/share/elasticsearch/config/certs:Z"

set_sysctl: true
