# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Install sensu-plugins
  command: sensu-install -p {{item}}
  with_items:
    - http
  tags:
    - monitoring

# Ensure the needed SELinux booleans are enabled
- name: Ensure the needed SELinux booleans are enabled
  seboolean: name={{item}} state=yes persistent=yes
  with_items:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
  tags:
    - dci-core

# Ensure dci-release is installed
- name: Ensure dci-release is installed (CentOS, RedHat)
  yum: name=http://packages.distributed-ci.io/dci-release.el7.noarch.rpm state=present
  when: ansible_distribution in ['CentOS', 'RedHat']
  tags:
    - dci-core

- name: Ensure dci-release is installed (Fedora)
  yum: name=http://packages.distributed-ci.io/dci-release.fc23.noarch.rpm state=present
  when: ansible_distribution in ['Fedora']
  tags:
    - dci-core

- name: Enable SCL
  yum: name=centos-release-scl state=present
  tags:
    - dci-core

# Ensure postgresql client tools are installed
- name: Ensure postgresql client tools installed
  yum: name=rh-postgresql94-postgresql state=present
  tags:
    - dci-core

# Ensure a backup of the database is made before
# any update takes place
- name: Ensure backup is made
  shell: . /opt/rh/rh-postgresql94/enable && swiftbackmeup backup --mode now
  when: swiftbackmeup_modes is defined
  tags:
    - dci-core

# Install DCI-API
#
- name: Ensure DCI is installed
  yum: name=dci-api state=latest update_cache=yes
  tags:
    - dci-core

# This is a temporary fix to remove once
# I9db68725d6c8cd05fa50a9052abed206fd7811dc is
# merged.
- name: ensure dci-dbsync exists
  stat: path=/usr/bin/dci-dbsync
  register: dci_dbsync_state
- name: Pull dci-common for pre-I9db68725d6c8cd05fa50a9052abed206fd7811dc rpm
  yum: name=dci-common state=latest
  when: dci_dbsync_state.stat.exists == False

# Configure DCI-API configuration file
#
- name: Ensure HOST is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^HOST =' line="HOST = '{{ apihost }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

- name: Ensure ES_HOST is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^ES_HOST =' line="ES_HOST = '{{ eshost }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

- name: Ensure SQLALCHEMY_DATABASE_URI is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^SQLALCHEMY_DATABASE_URI =' line="SQLALCHEMY_DATABASE_URI = 'postgresql://{{ dbuser }}:{{ dbpassword }}@{{ dbhost }}:5432/{{ dbname }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

# Configure Swift
#
- name: Ensure STORE_ENGINE is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^STORE_ENGINE =' line="STORE_ENGINE = '{{ store_engine }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

- name: Ensure STORE_USERNAME is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^STORE_USERNAME =' line="STORE_USERNAME = '{{ store_username }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

- name: Ensure STORE_PASSWORD is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^STORE_PASSWORD =' line="STORE_PASSWORD = '{{ store_password }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

- name: Ensure STORE_TENANT_NAME is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^STORE_TENANT_NAME =' line="STORE_TENANT_NAME = '{{ store_tenant_name }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

- name: Ensure STORE_AUTH_URL is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^STORE_AUTH_URL =' line="STORE_AUTH_URL = '{{ store_auth_url }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

- name: Ensure STORE_CONTAINER is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^STORE_CONTAINER =' line="STORE_CONTAINER = '{{ store_container }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

- name: Ensure ZMQ_CONN is configurerd in settings.py
  lineinfile: dest=/etc/dci-api/settings.py regexp='^ZMQ_CONN =' line="ZMQ_CONN = '{{ zmq_conn }}'"
  notify:
    - reload httpd
  tags:
    - dci-core

# Install DCI itself
#
- name: Check if db is already in place
  shell: psql -U {{ dbuser }} -h {{ dbhost }} -d {{ dbname }} -w -c 'SELECT * FROM users'
  environment:
    PGPASSWORD: '{{ dbpassword }}'
  register: dbexist
  ignore_errors: yes
  tags:
    - dci-core

- name: Initiate db schema
  command: dci-dbinit
  environment:
    DCI_LOGIN: admin
    DCI_PASSWORD: '{{ adminpassword }}'
  when: dbexist|failed
  tags:
    - dci-core

- name: Update the schema
  command: dci-dbsync
  become_user: apache
  environment:
    DCI_LOGIN: admin
    DCI_PASSWORD: '{{ adminpassword }}'
  when: dbexist|success
  tags:
    - dci-core

- name: Ensure apache can write files for DCI
  file: path='{{ api_filestore_path | default("/var/lib/dci-control-server/files") }}' state=directory owner=apache group=apache recurse=true

# Configure DCI-API vhost
#
- name: Create vhost file
  template: src=dci_api.conf dest=/etc/httpd/conf.d/dci_api.conf
  notify:
    - reload httpd
  tags:
    - dci-core

# Create a crontab to update ES in Async way
#
- name: Create cron to feed ES
  cron: name="AsyncES" minute="*/5" hour="*" job="/bin/dci-esindex > /dev/null"
