# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
# Ensure the needed SELinux booleans are enabled
- name: Ensure the needed SELinux booleans are enabled
  seboolean:
    name: '{{ item }}'
    state: yes
    persistent: yes
  with_items:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
  tags:
    - dci-core

- name: Enable SCL
  yum:
    name: centos-release-scl
    state: present
  tags:
    - dci-core

# Ensure postgresql client tools are installed
- name: Ensure postgresql client tools installed
  yum:
    name: rh-postgresql94-postgresql
    state: present
  tags:
    - dci-core

# Ensure a backup of the database is made before
# any update takes place
- name: Ensure backup is made
  shell: . /opt/rh/rh-postgresql94/enable && swiftbackmeup backup --mode now
  when: swiftbackmeup_modes is defined
  tags:
    - dci-core

- name: Ensure apache user is part of DCI group
  user:
    name: apache
    append: yes
    groups: dci

# Install DCI-API
#
- name: Ensure DCI is installed
  yum:
    name: dci-api
    state: latest
    update_cache: yes
  notify:
    - restart httpd
  tags:
    - dci-core

- name: Ensure DCI Client is installed
  yum:
    name: python2-dciclient
    state: latest
    update_cache: yes
  tags:
    - dci-core

# This is a temporary fix to remove once
# I9db68725d6c8cd05fa50a9052abed206fd7811dc is
# merged.
- name: ensure dci-dbsync exists
  stat:
    path: /usr/bin/dci-dbsync
  register: dci_dbsync_state

- name: Pull dci-common for pre-I9db68725d6c8cd05fa50a9052abed206fd7811dc rpm
  yum:
    name: dci-common
    state: latest
  when: dci_dbsync_state.stat.exists == False

# Install Repo certs to be able to generate client certificates
#
- name: Create SSL Directory
  file:
    path: '/etc/ssl/repo'
    state: directory
    recurse: yes
  tags:
    - dci-core

- name: Install Repo CA certs
  copy:
    content: "{{ repo_cacert }}"
    dest: "{{ repo_sslcacertfile }}"
  tags:
    - dci-core

- name: Install Repo CA key
  copy:
    content: "{{ repo_cakey }}"
    dest: "{{ repo_sslcakeyfile }}"
  tags:
    - dci-core

# Configure DCI-API configuration file
#
- name: Create dci-api settings file
  template:
    src: settings.py.j2
    dest: /etc/dci-api/settings.py
  notify:
    - reload httpd
  tags:
    - dci-core

# Install DCI itself
#
- name: Check if db is already in place
  shell: . /opt/rh/rh-postgresql94/enable && psql -U {{ dbuser }} -h {{ dbhost }} -d {{ dbname }} -w -c 'SELECT * FROM users'
  environment:
    PGPASSWORD: '{{ dbpassword }}'
  register: dbexist
  ignore_errors: yes
  tags:
    - dci-core

- name: Initiate db schema
  command: dci-dbinit
  environment:
    DCI_LOGIN: admin
    DCI_PASSWORD: '{{ adminpassword }}'
  when: dbexist|failed
  tags:
    - dci-core

- name: Update the schema
  command: dci-dbsync
  become_user: apache
  environment:
    DCI_LOGIN: admin
    DCI_PASSWORD: '{{ adminpassword }}'
  when: dbexist|success
  tags:
    - dci-core

- name: Ensure apache can write files for DCI
  file:
    path: '{{ api_filestore_path | default("/var/lib/dci-control-server/files") }}'
    state: directory
    owner: apache
    group: apache
    recurse: true

# Configure DCI-API vhost
#
- name: Create vhost file
  template:
    src: dci_api.conf
    dest: /etc/httpd/conf.d/dci_api.conf
  notify:
    - reload httpd
  tags:
    - dci-core
