---
# base system
simple_packages: []
simple_mounts: {}
simple_users: {}
simple_node_exporter: {}

# SSH access
simple_ssh_access: []

# firewalld
simple_firewalld_services: {}
simple_firewalld_ports: {}

# systemd services
simple_services: {}

# files
simple_files: {}

# containers
simple_quadlet_subnet: 192.168.100.0/24
simple_global_quadlets: {}
simple_group_quadlets: {}
simple_host_quadlets: {}
