---
# base system
simple_packages: []
simple_mounts: {}
simple_users: {}
simple_groups: {}
simple_node_exporter: {}

# SSH access
simple_ssh_access: []

# firewalld
simple_firewalld_monitoring_zone: prometheus
simple_firewalld_monitoring_ips:
  - 127.0.0.1
simple_global_firewalld_services: {}  # to define in group_vars/all
simple_group_firewalld_services: {}  # to define in group_vars/<group>
simple_firewalld_services: {}  # to define in host_vars
simple_global_firewalld_ports: {}  # to define in group_vars/all
simple_group_firewalld_ports: {}  # to define in group_vars/<group>
simple_firewalld_ports: {}  # to define in host_vars

# systemd services
simple_services: {}

# files
simple_files: {}

# containers
simple_quadlet_subnet: 192.168.100.0/24
simple_global_quadlets: {}  # to define in group_vars/all
simple_group_quadlets: {}  # to define in group_vars/<group>
simple_quadlets: {}  # to define in host_vars
