---
- name: Create image quadlet
  vars:
    _quadlet: podman-exporter
    _config: "{{ podman_exporter_container_spec }}"
  ansible.builtin.template:
    src: "global.image.j2"
    dest: "/etc/containers/systemd/{{ _quadlet }}.image"
    mode: '0644'
  notify:
    - Restart podman-exporter

- name: Create container quadlet
  vars:
    _quadlet: podman-exporter
    _config: "{{ podman_exporter_container_spec }}"
  ansible.builtin.template:
    src: "global.container.j2"
    dest: "/etc/containers/systemd/{{ _quadlet }}.container"
    mode: '0644'
  notify:
    - Restart podman-exporter

- name: Enable access to web port in firewall
  ansible.posix.firewalld:
    port: "{{ podman_exporter_http_port }}/tcp"
    zone: "{{ podman_exporter_firewalld_zone | default(omit) }}"
    state: enabled
    immediate: true
    permanent: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure service is started
  ansible.builtin.systemd:
    name: podman-exporter.service
    state: started
    daemon-reload: true
  ignore_errors: "{{ ansible_check_mode }}"
...
