# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Common-Configuration
  hosts: all
  remote_user: centos
  sudo: yes
  roles:
    - common
  tags:
    - dci-core

- name: Install-Sensu-client
  hosts: all
  remote_user: dci
  sudo: yes
  roles:
    - sensu-client
  tags:
    - monitoring

- name: Install-PostgreSQL
  hosts: postgresql
  remote_user: dci
  sudo: yes
  roles:
    - postgresql

- name: Install-ElasticSearch
  hosts: elasticsearch
  remote_user: dci
  sudo: yes
  roles:
    - elasticsearch

- name: Install-DCI-Control-Server
  hosts: dci-api
  remote_user: dci
  sudo: yes
  roles:
    - httpd
    - dci-api

- name: Install-WebAPP
  hosts: dci-ui
  remote_user: dci
  sudo: yes
  roles:
    - httpd
    - dci-ui

- name: Install-RabbitMQ
  hosts: rabbitmq
  remote_user: dci
  sudo: yes
  roles:
    - rabbitmq
  tags:
    - monitoring

- name: Install-Redis
  hosts: redis
  remote_user: dci
  sudo: yes
  roles:
    - { role: geerlingguy.redis }
  tags:
    - monitoring

- name: Install-sensu
  hosts: sensu
  remote_user: dci
  sudo: yes
  roles:
    - httpd
    - sensu
  tags:
    - monitoring

