# -*- encoding: utf-8 -*-
#
# Copyright 2015-2017 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Common-Configuration
  hosts: all
  become: yes
  roles:
    - common
    - prometheus-node-exporter
  tags:
    - dci-core
    - packages
    - doc

- name: Common Configuration for nodes inside Red Hat's network
  hosts: dci_internal
  become: yes
  tasks:
    - include_role:
        name: common
        tasks_from: rh-internal
        handlers_from: rh-internal
  tags:
    - dci-core
    - dci-internal

- name: Install-PostgreSQL
  hosts: dci_database
  become: yes
  roles:
    - postgresql
    - role: yolo_backup
      become_user: "{{ yolo_backup_user|default(dci) }}"

- name: Install httpd
  hosts: dci_api:dci_ui:dci_packages:dci_doc:dci_blog
  become: yes
  roles:
    - httpd

- name: Install-DCI-Control-Server
  hosts: dci_api
  become: yes
  roles:
    - dci-api

- name: Install-DCI-Worker
  hosts: dci_worker
  become: yes
  roles:
    - dci-worker

- name: Install-WebAPP
  hosts: dci_ui
  become: yes
  roles:
    - dci-ui

- name: Install-fail2ban
  hosts: all
  become: yes
  roles:
    - role: fail2ban
      when: fail2ban_disabled is not defined
  tags:
    - dci-core

- name: Install the packages node
  hosts: dci_packages
  become: yes
  roles:
    - packages
  tags:
    - packages

- name: Install the docs node
  hosts: dci_doc
  become: yes
  roles:
    - doc
  tags:
    - dci-core
    - doc

- name: Install the blog node
  hosts: dci_blog
  become: yes
  roles:
    - dci-blog
  tags:
    - dci-core
    - blog

- name: Install-Repo-Server
  hosts: dci_repo
  become: yes
  roles:
    - nginx
    - dci-repo
  tags:
    - dci-core

- name: Install DCI registry
  hosts: dci_registry
  become: yes
  roles:
    - registry
  tags:
    - registry

- name: Install DCI Feeder
  hosts: dci_feeder
  become: yes
  roles:
    - dci-feeder
  tags:
    - feeder

- name: Install DCI Elasticsearch
  hosts: dci_analytics
  become: yes
  roles:
    - elasticsearch
  tags:
    - elasticsearch
    - dci-core

- name: Install DCI Analytics
  hosts: dci_analytics
  become: yes
  roles:
    - dci-analytics
  tags:
    - dci-analytics
    - dci-core
