---
- name: Create the mock group
  group:
    name: mock

- name: Create the zuul user
  user:
    name: zuul
    comment: Zuul slave
    groups: mock
    home: /var/lib/zuul
    shell: /bin/bash
    uid: 1001

- name: Add SF zuul pub key
  authorized_key:
    user: zuul
    key: '{{ sf_zuul_pubkey }}'
  when: sf_zuul_pubkey is defined
