# -*- encoding: utf-8 -*-
#
# Copyright (C) 2017 Red Hat, Inc.
#
# Author: Dimitri Savineau <dsavinea@redhat.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "rhel-{{ ansible_distribution_major_version }}.yml"
    - "rhel-7.yml"

- name: Disable EPEL repository
  ini_file:
    path: '/etc/yum.repos.d/epel.repo'
    section: 'epel'
    option: 'enabled'
    value: 0
    no_extra_spaces: true

- name: Enable CentOS-PowerTools repository
  ini_file:
    path: '/etc/yum.repos.d/CentOS-PowerTools.repo'
    section: 'PowerTools'
    option: 'enabled'
    value: 1
    no_extra_spaces: true
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8'

- name: Fix /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: '{{ ansible_eth0.ipv4.address }} {{ ansible_hostname }}.{{ ansible_domain }} {{ ansible_hostname }}'

- name: Install Openstack packages
  package:
    name: "{{ item }}"
  with_items: "{{ openstack_packages }}"

- name: Copy MariaDB configuration
  template:
    src: swift.cnf
    dest: /etc/my.cnf.d/swift.cnf

- name: Ensure MariaDB is started
  service:
    name: mariadb
    state: started
    enabled: true

- name: Ensure Keystone DB are present
  mysql_db:
    name: keystone
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Ensure Keystone User is present
  mysql_user:
    name: keystone
    password: '{{ swift_ks_mysql_password }}'
    host: '{{ ansible_eth0.ipv4.address }}'
    priv: 'keystone.*:ALL'
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create keystone wsgi directory
  file:
    path: /var/www/cgi-bin/keystone
    state: directory
    owner: keystone
    group: keystone
    mode: '0755'

- name: Copy wsgi script
  copy:
    src: '/usr/bin/{{ item }}'
    dest: '/var/www/cgi-bin/keystone/{{ item.replace("wsgi-","") }}'
    owner: keystone
    group: keystone
    mode: '0644'
    remote_src: true
  with_items:
    - keystone-wsgi-public

- name: Copy Keystone configuration
  template:
    src: '{{ item }}'
    dest: '/etc/httpd/conf.d/{{ item }}'
  with_items:
    - keystone_wsgi_main.conf

- name: Copy Keystone configuration
  template:
    src: keystone.conf
    dest: /etc/keystone/keystone.conf
    owner: root
    group: keystone
    mode: '0640'

- name: Ensure credential/fernet directory
  file:
    path: '/etc/keystone/{{ item }}-keys'
    state: directory
    owner: keystone
    group: keystone
    mode: '0700'
  with_items:
    - credential
    - fernet

- name: Ensure httpd is started
  service:
    name: httpd
    state: restarted
    enabled: true

- name: Create the openrc
  template:
    src: openrc
    dest: '/home/{{ ansible_user }}/openrc'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- block:
  - name: Run Keystone dbsync
    shell: 'keystone-manage db_sync'
    become_user: keystone

  - name: Bootstrap Keystone fernet
    shell: 'keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone'

  - name: Bootstrap Keystone credential
    shell: 'keystone-manage credential_setup --keystone-user keystone --keystone-group keystone'

  - name: Boostrap Keystone
    shell: |
      keystone-manage bootstrap --bootstrap-password {{ swift_ks_admin_token }} \
      --bootstrap-admin-url http://{{ ansible_eth0.ipv4.address }}:5000/v3/ \
      --bootstrap-internal-url http://{{ ansible_eth0.ipv4.address }}:5000/v3/ \
      --bootstrap-public-url http://{{ ansible_host }}:5000/v3/ \
      --bootstrap-region-id regionOne

  - name: Create Swift auth
    shell: |
      source /home/{{ ansible_user }}/openrc
      openstack project create --domain default --description "Service Project" service
      openstack role create service
      openstack role create swiftoperator
      openstack role create user
      openstack user create --project service --password {{ swift_service_password }} swift
      openstack role add --project service --user swift admin
      openstack role add --project service --user admin admin
      openstack service create --name swift --description "OpenStack Object Storage" object-store
      openstack endpoint create --region regionOne object-store public http://{{ ansible_eth0.ipv4.address }}:8080/v1/AUTH_%\(tenant_id\)s
      openstack endpoint create --region regionOne object-store internal http://{{ ansible_host }}:8080/v1/AUTH_%\(tenant_id\)s
      openstack endpoint create --region regionOne object-store admin http://{{ ansible_eth0.ipv4.address }}:8080/v1
      openstack project create {{ store_tenant_name }}
      openstack user create --project {{ store_tenant_name }} --password {{ store_password }} {{ store_username }}
      openstack role add --project {{ store_tenant_name }} --user {{ store_username }} member
      openstack role add --project {{ store_tenant_name }} --user {{ store_username }} user
      openstack role add --project {{ store_tenant_name }} --user {{ store_username }} swiftoperator

  - name: Test volume device type
    stat:
      path: '/dev/{{ swift_volume_device }}'
    register: volume_type

  - name: Create a file block device
    command: |
      dd if=/dev/zero of=/dev/{{ swift_volume_device }} bs=1M count=1024
    when: volume_type.stat.isblk is undefined

  - name: Create Swift storage directory
    file:
      path: '/srv/node/{{ swift_volume_device }}'
      state: directory

  - name: Create xfs filesystem
    filesystem:
      fstype: xfs
      dev: '/dev/{{ swift_volume_device }}'
      force: true

  - name: Mount the swift volume
    mount:
      name: '/srv/node/{{ swift_volume_device }}'
      src: '/dev/{{ swift_volume_device }}'
      fstype: xfs
      opts: noatime,nodiratime,nobarrier,logbufs=8
      state: mounted

  - name: Set right Swift storage directory
    file:
      path: /srv/node
      state: directory
      owner: swift
      group: swift
      seuser: system_u
      serole: object_r
      setype: swift_data_t
      recurse: true

  when: swift_bootstrap|bool

- name: Copy Memcached configuration
  template:
    src: memcached
    dest: /etc/sysconfig/memcached

- name: Ensure Memcached is started
  service:
    name: memcached
    state: started
    enabled: true

- name: Copy Swift configuration
  template:
    src: '{{ item }}.conf'
    dest: '/etc/swift/{{ item }}.conf'
    owner: root
    group: swift
  with_items:
    - account-server
    - container-server
    - object-server
    - proxy-server
    - swift

- name: Set mode to Swift signing directory
  file:
    path: /var/cache/swift
    state: directory
    owner: swift
    group: swift
    mode: '0700'

- name: Create Swift ring
  shell: |
    swift-ring-builder /etc/swift/object.builder create 10 1 1
    swift-ring-builder /etc/swift/container.builder create 10 1 1
    swift-ring-builder /etc/swift/account.builder create 10 1 1
    swift-ring-builder /etc/swift/object.builder add r1z1-{{ ansible_eth0.ipv4.address }}:6000/{{ swift_volume_device }} 1
    swift-ring-builder /etc/swift/container.builder add r1z1-{{ ansible_eth0.ipv4.address }}:6001/{{ swift_volume_device }} 1
    swift-ring-builder /etc/swift/account.builder add r1z1-{{ ansible_eth0.ipv4.address }}:6002/{{ swift_volume_device }} 1
    swift-ring-builder /etc/swift/object.builder rebalance
    swift-ring-builder /etc/swift/container.builder rebalance
    swift-ring-builder /etc/swift/account.builder rebalance
  when: swift_bootstrap|bool

- name: Ensure Swift services are started
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - openstack-swift-proxy
    - openstack-swift-account
    - openstack-swift-account-auditor
    - openstack-swift-account-reaper
    - openstack-swift-account-replicator
    - openstack-swift-container
    - openstack-swift-container-auditor
    - openstack-swift-container-replicator
    - openstack-swift-container-updater
    - openstack-swift-object
    - openstack-swift-object-auditor
    - openstack-swift-object-replicator
    - openstack-swift-object-updater
