---
- name: Create SSL Directory
  file:
   path: '{{ item | dirname }}'
   state: directory
   recurse: yes
  with_items:
   - '{{ repo_sslcertificatefile }}'
   - '{{ repo_sslcertificatekeyfile }}'
   - '{{ repo_sslcacertfile }}'

- name: Install SSL Certificate file
  copy:
    content: "{{ repo_servercert }}"
    dest: "{{ repo_sslcertificatefile }}"

- name: Install SSL Certificate key file
  copy:
    content: "{{ repo_serverkey }}"
    dest: "{{ repo_sslcertificatekeyfile }}"

- name: Install SSL CA Certificate file
  copy:
    content: "{{ repo_cacert }}"
    dest: "{{ repo_sslcacertfile }}"

- name: Create the nginx root dir
  file:
    path: '{{ repo_rootdir }}'
    state: directory
    recurse: yes

- name: Install nginx Vhost
  template:
    src: templates/nginx.conf
    dest: /etc/opt/rh/rh-nginx112/nginx/nginx.conf
  notify:
    - reload nginx
