---
- name: Gather OS specific variables (postgres)
  include_vars: "{{ item }}"
  with_first_found:
    - "rhel-{{ ansible_distribution_major_version }}.yml"
    - "rhel-7.yml"

- name: Create SSL Directory
  file:
   path: '{{ repo_sslcacertfile | dirname }}'
   state: directory
   recurse: yes

- name: Ensure the needed SELinux booleans are enabled
  seboolean:
    name: '{{ item }}'
    state: yes
    persistent: yes
  with_items:
    - httpd_can_network_connect

- name: Install SSL Certificate file
  copy:
    content: "{{ repo_servercert }}"
    dest: "{{ repo_sslcertificatefile }}"
  when: repo_servercert is defined

- name: Install SSL Certificate key file
  copy:
    content: "{{ repo_serverkey }}"
    dest: "{{ repo_sslcertificatekeyfile }}"
  when: repo_serverkey is defined

- name: Install SSL CA Certificate file
  copy:
    content: "{{ repo_cacert }}"
    dest: "{{ repo_sslcacertfile }}"

- name: Create the nginx root dir
  file:
    path: '{{ repo_rootdir }}'
    state: directory
    recurse: no
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u

- name: Install nginx Vhost
  template:
    src: dci_repo.conf.j2
    dest: '/etc/{{nginx_scl_prefix_dir | default("") }}nginx/conf.d/dci_repo.conf'
  notify:
    - reload nginx

- name: Create the apache group
  group:
    name: apache
    gid: 48

- name: Create the apache user
  user:
    name: apache
    comment: Apache
    home: /usr/share/httpd
    shell: /sbin/nologin
    uid: 48
    group: apache

- name: Add dci feeder pub key
  authorized_key:
    user: root
    key: '{{ dci_feeder_pubkey }}'
  when: dci_feeder_pubkey is defined
