---
- name: Create SSL Directory
  file:
   path: '{{ repo_sslcacertfile | dirname }}'
   state: directory
   recurse: yes

- name: Install SSL Certificate file
  copy:
    content: "{{ repo_servercert }}"
    dest: "{{ repo_sslcertificatefile }}"
  when: repo_servercert is defined

- name: Install SSL Certificate key file
  copy:
    content: "{{ repo_serverkey }}"
    dest: "{{ repo_sslcertificatekeyfile }}"
  when: repo_serverkey is defined

- name: Install SSL CA Certificate file
  copy:
    content: "{{ repo_cacert }}"
    dest: "{{ repo_sslcacertfile }}"

- name: Create the nginx root dir
  file:
    path: '{{ repo_rootdir }}'
    state: directory
    recurse: yes
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u

- name: Install nginx Vhost
  template:
    src: dci_repo.conf.j2
    dest: /etc/opt/rh/rh-nginx112/nginx/conf.d/dci_repo.conf
  notify:
    - reload nginx
