# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Ensure rubygems is installed for Sensu plugins
  yum: name=rubygems state=present

- name: Install Sensu plugins checks dependencies
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - gcc-c++
    - bc

- name: Install sensu repositories
  copy: src=sensu.repo dest=/etc/yum.repos.d/sensu.repo

- name: Install sensu client
  yum: name=sensu state=present

- name: Generate sensu config.json
  template: src={{item}}.json dest=/etc/sensu/conf.d/{{item}}.json
  with_items:
    - config
    - client
  notify:
    - reload sensu-client

- name: Install sensu-plugins
  command: sensu-install -p {{item}}
  sudo: yes
  with_items:
    - disk-checks
    - network-checks
    - memory-checks
    - mailer
    - load-checks
    - ntp
    - dns

- name: Start sensu
  service: name=sensu-client state=started enabled=yes

