---
- name: Install xinetd
  package:
    name: xinetd

- name: Copy the xinetd file
  copy:
    src: xinetd_feeder
    dest: /etc/xinetd.d/feeder

- name: Start xinetd
  service:
    name: xinetd
    state: started
    enabled: True
