---
- name: Reload systemd for dci-analytics
  systemd:
    daemon_reload: yes

- name: Restart dci-analytics container
  systemd:
    name: "dci-analytics.service"
    state: restarted
    enabled: yes

- name: Restart dci-analytics-worker container
  systemd:
    name: "dci-analytics-worker.service"
    state: restarted
    enabled: yes

- name: Restart dci-analytics-sync timer
  systemd:
    name: dci-analytics-sync.timer
    state: restarted
    enabled: yes

- name: Restart dci-rabbitmq container
  systemd:
    name: dci-rabbitmq.service
    state: restarted
    enabled: yes
