---
openstack_packages:
  - mariadb-server
  - memcached
  - openstack-keystone
  - openstack-selinux
  - openstack-swift
  - openstack-swift-proxy
  - openstack-swift-account
  - openstack-swift-container
  - openstack-swift-object
  - python3-keystoneclient
  - python3-memcached
  - python3-openstackclient
  - python3-swiftclient
