---
openstack_packages:
  - mariadb-server
  - memcached
  - openstack-keystone
  - openstack-selinux
  - openstack-swift
  - openstack-swift-proxy
  - openstack-swift-account
  - openstack-swift-container
  - openstack-swift-object
  - python-keystoneclient
  - python-memcached
  - python-openstackclient
  - python-swiftclient
