---
haproxy_user: root
haproxy_group: root
haproxy_listen_http_port: 80
haproxy_listen_https_port: 443
haproxy_config_dir: /etc/haproxy
haproxy_container_image: docker.io/haproxytech/haproxy-alpine:3.0
haproxy_stats_port: 8404
haproxy_prometheus_exporter_port: 8405
haproxy_container_ports:
  - "{{ haproxy_stats_port }}:{{ haproxy_stats_port }}"
  - "{{ haproxy_prometheus_exporter_port }}:{{ haproxy_prometheus_exporter_port }}"
  - "{{ haproxy_listen_http_port }}:80"
  - "{{ haproxy_listen_https_port }}:443"
haproxy_container_volumes:
  - "{{ haproxy_config_dir }}:{{ haproxy_config_dir }}:ro,z"
  - /etc/letsencrypt:/etc/letsencrypt:ro,z
haproxy_container_network: quadlet.network
haproxy_container_spec:
  image: "{{ haproxy_container_image }}"
  no_quadlet_image: true
  ports: "{{ haproxy_container_ports }}"
  volumes: "{{ haproxy_container_volumes }}"
  network: "{{ haproxy_container_network }}"
  command: "haproxy -f {{ haproxy_config_dir }}"
  reload_commands:
    - podman exec haproxy haproxy -f {{ haproxy_config_dir }} -c
    - podman kill --signal USR2 haproxy
  labels:
    io.distributed-ci.svc: haproxy
...
