# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Install sensu-plugins
  command: sensu-install -p {{item}}
  with_items:
    - http
  tags:
    - monitoring

# Ensure dci-release is installed
- name: Ensure dci-release is installed (CentOS, RedHat)
  yum: name=http://dci.enovance.com/dci-release.el7.noarch.rpm state=present
  when: ansible_distribution in ['CentOS', 'RedHat']
  tags:
    - dci-core

- name: Ensure dci-release is installed (Fedora)
  yum: name=http://dci.enovance.com/dci-release.fc23.noarch.rpm state=present
  when: ansible_distribution in ['Fedora']
  tags:
    - dci-core

# Install DCI-UI
#
- name: Ensure DCI-UI is installed
  yum: name=dci-ui state=latest update_cache=yes
  notify:
    - reload httpd
  tags:
    - dci-core

# Configure DCI-UI config.json
#
- name: Ensure apiURL is configurerd in config.json
  lineinfile: dest=/etc/dci-ui/config.json regexp='"apiURL":' line='"apiURL":"http://{{ apihost }}",'
  notify:
    - reload httpd
  tags:
    - dci-core

# Configure DCI-UI vhost
#
- name: Create vhost file
  template: src=dci_ui.conf dest=/etc/httpd/conf.d/dci_ui.conf
  notify:
    - reload httpd
  tags:
    - dci-core
