# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "rhel-{{ ansible_distribution_major_version }}.yml"
    - "rhel-7.yml"

- name: Ensure EPEL is installed
  package:
    name: epel-release
    state: present

- name: Ensure ca-certificates is up to date
  package:
    name: ca-certificates
    update_cache: yes
    state: latest

- name: Remove python2-distro package
  package:
    name: python2-distro
    state: absent

- name: Ensure Priority is installed
  package:
    name: yum-plugin-priorities
    state: present
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == '7'

- name: Install DCI packages GPG key
  rpm_key:
    key: "https://packages.distributed-ci.io/RPM-GPG-KEY-distributedci"
    state: present

- name: Ensure dci-release is installed
  package:
    name: "http://packages.distributed-ci.io/dci-release.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  tags:
    - dci-core

- name: Add DCI Extras
  yum_repository:
    name: DCI-Extras
    description: DCI Extras YUM repo
    baseurl: https://packages.distributed-ci.io/repos/extras/el/$releasever/$basearch/
    priority: "1"
    gpgcheck: no

- name: Add RDO Repository
  yum_repository:
    name: RDO-OpenStack
    description: RDO YUM repo
    baseurl: http://mirror.centos.org/centos/{{ releasever }}/cloud/$basearch/openstack-{{ openstack_version }}/
    exclude: python-zmq, zeromq
    gpgcheck: no

- name: Install chrony
  package:
    name: chrony
    state: present
  tags:
    - molecule-notest

- name: Start chronyd service
  service:
    name: chronyd
    state: started
    enabled: yes
  tags:
    - molecule-notest

- name: Set the server hostname
  hostname:
    name: '{{ ansible_ssh_host }}'
  tags:
    - molecule-notest

- name: Ensure semanage is installed for SELinux boolean manipulation
  package:
    name: "{{ python_policycoreutils }}"
    state: present
  tags:
    - molecule-notest

- name: Ensure SELinux is enforced
  selinux:
    state: enforcing
    policy: targeted
  tags:
    - molecule-notest

- name: Ensure dci-sshpubkeys is installed
  package:
    name: dci-sshpubkeys
    state: present

- name: Ensure packages are up to their latest release
  package:
    name: '*'
    state: latest
    update_cache: yes
    exclude:
      - dci-feeder-api
      - dci-control-server
      - dci-umb
      - "{{ dciclient_package }}"
      - "{{ dciauth_package }}"
  tags:
    - molecule-notest
