# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Attach Red Hat pool
  redhat_subscription: state=present
                       username={{ rhn_user }}
                       password={{ rhn_password }}
                       pool={{ rhn_pool }}
  when: ansible_distribution == 'RedHat'

- name: Subscribe to Red Hat channels
  command: yum-config-manager --save --setopt "{{ item }}.enabled = 1"
  when: ansible_distribution == 'RedHat'
  with_items:
    - rhel-7-server-extras-htb-rpms    # python-werkzeug
    - rhel-7-server-openstack-5.0-rpms # python-flask, python-passlib
    - rhel-7-server-openstack-7.0-rpms # python-elasticsearch
    - rhel-7-server-ose-3.1-rpms       # ansible, elasticsearch
    - rhel-7-server-optional-rpms      # For EPEL use
    - rhel-7-server-extras-rpms        # For EPEL use
    - rhel-server-rhscl-7-rpms         # RHSCL for PostgreSQL 9.4

- name: Ensure EPEL is installed (CentOS)
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS'

# NOTE(spredzy): python-flask-sqlalchemy is not packaged in Red Hat
- name: Ensure EPEL is installed (RedHat)
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: ansible_distribution == 'RedHat'

- name: Ensure Priority is installed
  yum: name=yum-plugin-priorities state=present

# Ensure dci-release is installed
- name: Ensure dci-release is installed (CentOS, RedHat)
  yum: name=http://packages.distributed-ci.io/dci-release.el7.noarch.rpm state=present
  when: ansible_distribution in ['CentOS', 'RedHat']
  tags:
    - dci-core

- name: Ensure dci-release is installed (Fedora)
  yum: name=http://packages.distributed-ci.io/dci-release.fc23.noarch.rpm state=present
  when: ansible_distribution in ['Fedora']
  tags:
    - dci-core

- name: Add RDO Repository
  yum_repository:
    name: RDO-OpenStack
    description: RDO YUM repo
    baseurl: http://mirror.centos.org/centos/$releasever/cloud/$basearch/openstack-mitaka/
    exclude: python-zmq, zeromq
    gpgcheck: no
  when: ansible_distribution in ['CentOS', 'RedHat']

# stop chrony before starting ntpd
- name: Stop chrony service if it exists
  service: name=chronyd state=stopped enabled=no
  register: command_result
  failed_when: "command_result|failed and 'not find' not in commmand_result.msg"

# TODO(spredzy): To remove when the ntp sensu check support chrony
- yum: name=ntp state=present
- service: name=ntpd state=started enabled=yes

- name: Set the server hostname
  hostname: name={{ ansible_ssh_host }}

- name: Ensure semanage is installed for SELinux boolean manipulation
  yum: name=policycoreutils-python state=present

- name: Ensure SELinux is enforced
  selinux: state=enforcing policy=targeted

- name: Ensure dci-sshpubkeys is installed (CentOS, RHEL)
  yum: name=http://packages.distributed-ci.io/dci-sshpubkeys.el7.noarch.rpm state=present
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: Ensure dci-sshpubkeys is installed (Fedora)
  yum: name=http://packages.distributed-ci.io/dci-sshpubkeys.fc23.noarch.rpm state=present
  when: ansible_distribution in ['Fedora']

- name: Ensure packages are up to their latest release
  yum: name=* state=latest update_cache=yes
