---
- name: restart dci-worker
  systemd:
    name: dci-worker
    state: restarted
    daemon_reload: yes
  listen: "dci-control-server package upgraded"

- name: Set a fact to notify other plays that the dci-control-server package has been upgraded
  set_fact:
    dci_control_server_package_upgraded: True
  listen: "dci-control-server package upgraded"
