---
- name: restart dci-worker
  systemd:
    name: dci-worker
    state: restarted
    daemon_reload: yes
  listen: "dci-control-server upgraded"

- name: Set a fact to notify other plays that dci-control-server has been upgraded
  set_fact:
    dci_control_server_upgraded_fact: True
  listen: "dci-control-server upgraded"
