---
- name: Turn on persistent journal
  ansible.builtin.file:
    path: /var/log/journal
    owner: root
    group: systemd-journal
    mode: '2755'
    state: directory
    setype: var_log_t

- name: Set host name
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ simple_domainname }}"
    use: systemd

- name: Mount file systems
  ansible.posix.mount:
    path: "{{ item.key }}"
    src: "{{ item.value.src }}"
    fstype: "{{ item.value.fstype }}"
    state: "{{ item.value.state | default('mounted') }}"
    opts: "{{ item.value.opts | default(['defaults']) | join(',') }}"
  loop: "{{ simple_mounts | ansible.builtin.dict2items }}"
  loop_control:
    label: "{{ item.value.src }} -> {{ item.key }} ({{ item.value.fstype }})"

- name: Make sure RH insights is installed
  ansible.builtin.package:
    name: insights-client
    state: present

- name: Subscribe system RHN
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ simple_rhn_activation_key }}"
    org_id: "{{ simple_rhn_org_id }}"

- name: Configure tags for insights
  ansible.builtin.template:
    src: insights-tags.yaml.j2
    dest: /etc/insights-client/tags.yaml
    mode: "0644"

- name: Register to RH insights
  ansible.builtin.command:
    cmd: insights-client --register
    creates: /etc/insights-client/machine-id
...
