---
- name: Turn on persistent journal
  ansible.builtin.file:
    path: /var/log/journal
    owner: root
    group: systemd-journal
    mode: '2755'
    state: directory
    setype: var_log_t

- name: Set host name
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ simple_domainname }}"
    use: systemd

- name: Mount file systems
  ansible.posix.mount:
    path: "{{ item.key }}"
    src: "{{ item.value.src }}"
    fstype: "{{ item.value.fstype }}"
    state: "{{ item.value.state | default('mounted') }}"
    opts: "{{ item.value.opts | default(['defaults']) | join(',') }}"
  loop: "{{ simple_mounts | ansible.builtin.dict2items }}"
  loop_control:
    label: "{{ item.value.src }} -> {{ item.key }} ({{ item.value.fstype }})"

- name: Make sure RH insights is installed
  ansible.builtin.package:
    name: insights-client
    state: present

- name: Subscribe system RHN
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ simple_rhn_activation_key }}"
    org_id: "{{ simple_rhn_org_id }}"

- name: Configure tags for insights
  ansible.builtin.template:
    src: insights-tags.yaml.j2
    dest: /etc/insights-client/tags.yaml
    mode: "0644"

- name: Register to RH insights
  ansible.builtin.command:
    cmd: insights-client --register
    creates: /etc/insights-client/machine-id

- name: Build node_exporter configuration
  ansible.builtin.set_fact:
    __node_exporter: "{{ _default_node_exporter | ansible.builtin.combine(simple_node_exporter) }}"

- name: Check if node_exporter binary is present
  ansible.builtin.stat:
    path: "{{ __node_exporter.bin }}-{{ __node_exporter.version }}"
  register: __bin

- name: Download and install node_exporter
  when:
    - not __bin.stat.exists
    - not ansible_check_mode
  block:
    - name: Set temp dir fact
      ansible.builtin.set_fact:
        __tmp_dir: "/tmp/node_exporter-{{ __node_exporter.version }}"

    - name: Create temp dir
      ansible.builtin.file:
        path: "{{ __tmp_dir }}"
        state: directory
        mode: "0750"

    - name: Download node_exporter tarball
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ __node_exporter.version }}/node_exporter-{{ __node_exporter.version }}.linux-amd64.tar.gz"
        dest: "{{ __tmp_dir }}"
        mode: "0660"

    - name: Unarchive node_exporter tarball
      ansible.builtin.unarchive:
        src: "{{ __tmp_dir }}/node_exporter-{{ __node_exporter.version }}.linux-amd64.tar.gz"
        dest: "{{ __tmp_dir }}"
        extra_opts: "--strip-components=1"
        remote_src: true

    - name: Copy binary to binary location
      ansible.builtin.copy:
        src: "{{ __tmp_dir }}/node_exporter"
        dest: "{{ __node_exporter.bin }}-{{ __node_exporter.version }}"
        remote_src: true
        mode: "0755"
        owner: root
        group: root

    - name: Symlink binary
      ansible.builtin.file:
        src: "{{ __node_exporter.bin }}-{{ __node_exporter.version }}"
        dest: "{{ __node_exporter.bin }}"
        state: link

    - name: Remove temp dir
      ansible.builtin.file:
        path: "{{ __tmp_dir }}"
        state: absent

- name: Create node_exporter systemd unit file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0660"

- name: Manage node_exporter service
  ansible.builtin.systemd_service:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode
...
