---
- name: Ensure podman packages are present
  ansible.builtin.package:
    name:
      - podman
      - podman-plugins
    state: present

- name: Create quadlet subnet configuration
  vars:
    __subnet: "{{ simple_quadlet_subnet }}"
  ansible.builtin.template:
    src: quadlet.network.j2
    dest: /etc/containers/systemd/quadlet.network
    mode: "0644"

- name: Quadlet creation
  vars:
    __quadlet: "{{ item.key }}"
    __config: "{{ item.value }}"
  ansible.builtin.include_tasks:
    file: quadlet.yml
  loop: "{{ simple_global_quadlets | ansible.builtin.combine(simple_group_quadlets) | ansible.builtin.combine(simple_quadlets) | ansible.builtin.dict2items }}"
  loop_control:
    label: "{{ item.key }}"
...
