---
- name: Create directory path from file list
  ansible.builtin.file:
    path: "{{ item.key | dirname }}"
    state: directory
    mode: "{{ item.value.dir_mode | default(omit) }}"
    owner: "{{ item.value.owner | default(omit) }}"
    group: "{{ item.value.group | default(omit) }}"
  loop: "{{ simple_files | ansible.builtin.dict2items }}"
  loop_control:
    label: "{{ item.key | dirname }}"

- name: Create files from file list
  ansible.builtin.copy:
    dest: "{{ item.key }}"
    src: "{{ item.value.src | default(omit) }}"
    content: "{{ item.value.content | default(omit) }}"
    mode: "{{ item.value.mode | default(omit) }}"
    owner: "{{ item.value.owner | default(omit) }}"
    group: "{{ item.value.group | default(omit) }}"
  loop: "{{ simple_files | ansible.builtin.dict2items }}"
  loop_control:
    label: "{{ item.key }}"
...
