---
- name: Manage zone
  ansible.posix.firewalld:
    zone: "{{ _config.zone }}"
    state: present
    permanent: true
  register: _zone_result

- name: Reload firewalld if zone was created  # noqa: no-changed-when no-handler
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  when:
    - _zone_result.changed | bool
    - not ansible_check_mode

- name: Set zone sources  # noqa: ignore-errors
  ansible.posix.firewalld:
    zone: "{{ _config.zone }}"
    source: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  when: _config.source is defined
  ignore_errors: "{{ ansible_check_mode }}"
  loop: "{{ _config.source | list }}"
...
