---
- name: Install python firewalld bindings
  ansible.builtin.package:
    name:
      - python3-firewall

- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Build final firewalld configuration
  ansible.builtin.set_fact:
    _firewalld_config: "{{ _firewalld_config | default([]) + hostvars[inventory_hostname][item] }}"
  loop: "{{ hostvars[inventory_hostname].keys() }}"
  when:
    - item.startswith("simple_firewalld_rules_")

- name: Apply FirewallD config
  ansible.builtin.include_tasks:
    file: firewalld.yml
  loop: "{{ _firewalld_config }}"
  loop_control:
    loop_var: _config
...
