---
- name: Install python firewalld bindings
  ansible.builtin.package:
    name:
      - python3-firewall

- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Apply FirewallD config
  ansible.builtin.include_tasks:
    file: firewalld.yml
  loop: "{{ simple_firewalld_config }}"
  loop_control:
    loop_var: _config
...
