---
- name: Import SELinux tasks
  ansible.builtin.import_tasks:
    file: selinux.yml
  tags:
    - selinux

- name: Import base tasks
  ansible.builtin.import_tasks:
    file: base.yml
  tags:
    - base

- name: Import package tasks
  ansible.builtin.import_tasks:
    file: packages.yml
  tags:
    - packages

- name: Import DCI tasks
  ansible.builtin.import_tasks:
    file: dci.yml
  tags:
    - dci

- name: Import user tasks
  ansible.builtin.import_tasks:
    file: users.yml
  tags:
    - users

- name: Import firewall tasks
  ansible.builtin.import_tasks:
    file: firewall.yml
  tags:
    - firewall

- name: Import SSH tasks
  ansible.builtin.import_tasks:
    file: ssh.yml
  tags:
    - ssh

- name: Import directory tasks
  ansible.builtin.import_tasks:
    file: dirs.yml
  tags:
    - dirs

- name: Import file tasks
  ansible.builtin.import_tasks:
    file: files.yml
  tags:
    - files
...
