---
- name: Manage image quadlet
  ansible.builtin.template:
    src: quadlet.image.j2
    dest: "/etc/containers/systemd/{{ __quadlet }}.image"
    mode: "0644"
  register: __image
  notify: Restart quadlets

- name: Manage container quadlet
  ansible.builtin.template:
    src: quadlet.container.j2
    dest: "/etc/containers/systemd/{{ __quadlet }}.container"
    mode: "0644"
  register: __container
  notify: Restart quadlets

# if the image or container definition changed, this should trigger a restart
- name: Append to list of quadlets to restart  # noqa: no-handler
  ansible.builtin.set_fact:
    _simple_quadlets_to_restart: "{{ _simple_quadlets_to_restart | default([]) + [__quadlet] }}"
  when: >
    __image.changed | bool or
    __container.changed | bool

- name: Ensure service state is started
  ansible.builtin.systemd_service:
    name: "{{ __quadlet }}"
    state: started
    daemon-reload: true
  when: not ansible_check_mode
...
