---
feeder_dci_client_id: feeder/CHANGEME
feeder_dci_api_secret: shhh_dont_talk_about_it
feeder_registry_url: registry.example.com
feeder_registry_user: admin_registry_user
feeder_registry_password: shhh_dont_say_it

ssl_enabled: false
apihost: api.example.com

feeder_store_components_container: dummy
feeder_aws_access_key: dummy
feeder_aws_secret_access_key: dummy
feeder_aws_region: dummy
feeder_s3_endpoint_url: ""
feeder_aws_signature_version: v4

feeder_smtp_host: smtp.example.com
feeder_smtp_port: 25
feeder_smtp_username: ""
feeder_smtp_password: ""


feeder_google_chat_space_id: dummy
feeder_google_chat_key: dummy
feeder_google_chat_token: dummy
feeder_google_chat_thread_id: dummy
feeder_google_chat_kni_thread_id: dummy

feeder_ocp_pullsecret_json: '"dummy"'
feeder_ocp_pullsecret_file: /etc/dci-feeder-api/ocp-pull-secret.json

feeder_rq_queue_name: dcifeeder
feeder_rq_redis_host: localhost